# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.7.3'

gem 'coffee-rails'
gem 'jbuilder'
gem 'jquery-rails'
gem 'pg'
gem 'rails'
gem 'sass-rails'
gem 'sdoc', group: :doc
gem 'turbolinks'
gem 'uglifier'

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails'
end

group :development do
  gem 'spring'
  gem 'web-console', '~> 2.0'
end
